# Install from https://github.com/wlandau/parallelRemake
# Also requires the remake package at https://github.com/richfitz/remake
# and GNU make.
library(parallelRemake) 

# Encode remake/YAML instructions to generate multiple datasets
# and take the column means of each dataset.
for(rep in 1:4){ 
  dataset = paste0("dataset", rep)  
  column_means = paste0("column_means", rep) 
 
  # Initialize YAML fields.
  fields = list(
    sources = "code.R",
    targets = list(
      all = list(depends = column_means)
    )
  )

  # Add a target to create the data.
  # The `strings` function converts general R expressions into named character vectors.
  # Try `strings(x = myfunction(n = 5), y = 2)`.
  fields$targets[[dataset]] = list(command = strings(generate_data()))

  # Add a target to take the column means of a dataset.
  my_command = paste0("colMeans(dataset", rep, ")")
  fields$targets[[column_means]] = list(command = my_command)

  # Write the YAML file for remake.
  write_yaml(fields, paste0("step", rep, ".yml"))
}

# Write the remake/YAML file for plotting the column means of the datasets
# initialize YAML fields
fields = list(
  sources = "code.R",
  packages = "parallelRemake", # needed for `remember`
  targets = list(
    all = list(depends = "my_plot.pdf"),
    my_plot.pdf = list(
      command = strings(my_plot(column_means)),
      plot = "TRUE"
    ),

    # Remember the column means from the previous instances of remake
    column_means = list(command = strings(
      remember(I("column_means1"), I("column_means2"), I("column_means3"), I("column_means4"))
    ))
  )
)

# Write the plotting YAML file
write_yaml(fields, "my_plot.yml")

# Organize the steps of analysis into parallelizable stages.
stages = list(
  data = paste0("step", 1:4, ".yml"),
  plot = strings(my_plot.yml) # Try `strings(x = myfunction(n = 5), y = 2)`.
)

# Write the overarching Makefile for the workflow.
write_makefile(stages)

# Now, open a command line program run the workflow with `make`. 
# To run the steps in stage 1 in parallel, try `make -j 4`.
# To remove the files generated by `make`, run `make clean`.
